name: planten_app_final
description: Een planten dashboard app met ESP32 vochtigheidssensoren
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  google_fonts: ^6.1.0
  fl_chart: ^0.66.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/leaves.png
    - assets/albizia.png
    - assets/paulownia.png
